### ISSUE TITLE
Can't build TaskExplorer from sources

### ISSUE THREAD

**Issue by greenozon** [DavidXanatos/TaskExplorer#86]
There are many compiler issues like

```
c:\Prg\TaskExplorer-1.6.2\ProcessHacker\phlib\include\phnative.h(3417,11): error C2061: syntax error: identifier 'MACHINE_ATTRIBUTES' (compiling source file API\Windows\DnsResolver.cpp)
c:\Prg\TaskExplorer-1.6.2\ProcessHacker\phlib\include\phnative.h(3417,11): error C2061: syntax error: identifier 'MACHINE_ATTRIBUTES' (compiling source file API\Windows\Finders\WinHandleFinder.cpp)
c:\Prg\TaskExplorer-1.6.2\ProcessHacker\phlib\include\phnative.h(3417,11): error C2061: syntax error: identifier 'MACHINE_ATTRIBUTES' (compiling source file API\Windows\Finders\WinStringFinder.cpp)
c:\Prg\TaskExplorer-1.6.2\ProcessHacker\phlib\include\phnative.h(3417,11): error C2061: syntax error: identifier 'MACHINE_ATTRIBUTES' (compiling source file API\Windows\Finders\WinModuleFinder.cpp)
c:\Prg\TaskExplorer-1.6.2\ProcessHacker\phlib\include\phnative.h(3417,11): error C2061: syntax error: identifier 'MACHINE_ATTRIBUTES' (compiling source file API\Windows\Monitors\WinDbgMonitor.cpp)

```

and more!

I can't find the symbol `MACHINE_ATTRIBUTES`
in WInSDK:

"c:\Program Files (x86)\Windows Kits\10\Include\" 

MS VS 2019

**Comment by greenozon** [comment]
@DavidXanatos 
Some files are missed in the repo, any chance to add it please?

![Image](https://github.com/user-attachments/assets/0c3076c5-1286-4db2-84ab-5e1b4fdf3bed)

**Comment by DavidXanatos** [comment]
fixed https://github.com/DavidXanatos/TaskExplorer/tree/master/MiscHelpers/Archive

**Comment by greenozon** [comment]
Thanks a lot!  @DavidXanatos 
it partially solved the issues

Could you hint me also about these missed symbols?

![Image](https://github.com/user-attachments/assets/25b6bc1a-ea8e-4c17-9cd6-94b83de9c208)

**Comment by greenozon** [comment]
Shouldn't all those missed be inside the
\ProcessHacker\kphlib\include\kphapi.h ?

**Comment by DavidXanatos** [comment]
https://github.com/DavidXanatos/TaskExplorer/tree/master/KSystemHacker
its a fork of the old process hacker driver before all the changes, currently not used for anything but comes in handy as i may want to add features to it that MS would never sign, so its for use on systems where the user is in charge of signing their own drivers, or in test signing mode.

**Comment by greenozon** [comment]
OK, thanks fo fast reply!

Idea - 
if it's not used then I suggest to remove those (old) files fom TaskExplorer solution... ?

2) just hit another issue - the are some refs to lib named phlib.lib

when I tried to build it out it fails as well, any clues?...

![Image](https://github.com/user-attachments/assets/41abf9d9-7da0-403a-806d-333e5607c9e6)

**Comment by DavidXanatos** [comment]
you must first build
TaskExplorer\ProcessHacker\SystemInformer.sln 
with its dependencies 
TaskExplorer\ProcessHacker\tools\thirdparty\thirdparty.sln

I just added the old driver recently, I'd liek to keep it around for testing and debugging, but it shoudl be disabled from the reelase build for now.

**Comment by greenozon** [comment]
thanks
I was able to build thirdparty.lib  but not the TaskExplorer\ProcessHacker\SystemInformer.sln

see errors in my prev post
I got that FSBPIO_OUTFL_COMPATIBLE_STORAGE_DRIVER/etc  are windows 11 only guys
but how to build it out on a not that modern SDK?

maybe wrapping it by #ifdef  would be a good idea though?

**Comment by greenozon** [comment]
Side question -

```
c:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\ProcessHacker\tools\CustomBuildTool\bin\Release\x86>CustomBuildTool.exe
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '9.0.0' was not found.
  - The following frameworks were found:
      3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

is it possible to build using .NET8 instead of 9?
I did install .net9 but the error is still the same...
do I need x86 version of 32 one?

**Comment by greenozon** [comment]
I've installed this  - 

![Image](https://github.com/user-attachments/assets/683cef31-0b0d-4ef9-b7ca-33a2957c0515)

and seems the tool is happy, but.. .still fails - 


![Image](https://github.com/user-attachments/assets/70df6413-9926-4e37-b789-be811e27c79e)


any clues?

**Comment by DavidXanatos** [comment]
I build it on a VM with the latest win 11 SDK its to much work to ifdef things each time i want to update the phlib.
So the request for older SDK compatibility should be better directed at the SystemInformer project.

to the last error: did you create the private key for signing?

**Comment by greenozon** [comment]
Good point, thx for the hint!

maybe the last one - 

```
Build started...
1>------ Build started: Project: TaskExplorer, Configuration: Debug x64 ------
1>LINK : fatal error LNK1104: cannot open file '..\x64\Debug\qwt.lib'
1>Done building project "TaskExplorer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

how to build the qwt.lib?

**Comment by DavidXanatos** [comment]
build: https://github.com/DavidXanatos/TaskExplorer/blob/master/qwt/qwt/qwt.sln

**Comment by greenozon** [comment]
Thanks!

while building qwt hit this one -

```
1>   Creating library C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\qwt\qwt\x64\Debug\qwt.lib and object C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\qwt\qwt\x64\Debug\qwt.exp
1>qwt.vcxproj -> C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\qwt\qwt\x64\Debug\qwt.dll
1>The system cannot find the path specified.
1>The system cannot find the path specified.
1>C:\Dev\VS2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: The command "cmd /c "cd "C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\qwt\qwt\ProcessHacker\" & "C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\qwt\qwt\ProcessHacker\tools\CustomBuildTool\bin\Release\x86\CustomBuildTool.exe" -kph-sign "C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\qwt\qwt\x64\Debug\qwt.dll""
1>C:\Dev\VS2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "qwt.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by greenozon** [comment]
nope, one mo question :)

```
7>------ Build started: Project: TaskExplorer, Configuration: Debug x64 ------
7>   Creating library C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\x64\Debug\TaskExplorer.lib and object C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\x64\Debug\TaskExplorer.exp
7>LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
7>LINK : warning LNK4199: /DELAYLOAD:uxtheme.dll ignored; no imports found from uxtheme.dll
7>LINK : warning LNK4199: /DELAYLOAD:version.dll ignored; no imports found from version.dll
7>MemoryEditor.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl QHexEditor::sellect(__int64,__int64)" (?sellect@QHexEditor@@UEAAX_J0@Z)
7>C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\x64\Debug\\TaskExplorer.exe : fatal error LNK1120: 1 unresolved externals
7>Done building project "TaskExplorer.vcxproj" -- FAILED.
========== Build: 6 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by DavidXanatos** [comment]
update to latest github version and rebuild there were soem typo fixes sellect is written with one l

**Comment by greenozon** [comment]
Hurrey! FINALLY :)

1>TaskExplorer.vcxproj -> C:\Tmp\TaskExplorer\src\TaskExplorer-1.6.2\x64\Debug\TaskExplorer.exe
1>Done building project "TaskExplorer.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

but... can't run :)

---------------------------
TaskExplorer.exe - System Error
---------------------------
The program can't start because Qt5Svgd.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

**Comment by greenozon** [comment]
OK, seems I need release build...

Thanks for support David!

**Comment by DavidXanatos** [comment]
debug build shoudl also run just ensure you start it from VS or have the right Qt Binaries in your PATH variable, 
look in my release to know whcih files oyu need if you want to manually copy them in your output directory.

debug qt binaries have a "d.dll" sufix release binaries just ".dll"
